title: "Digital Derricke"
author:
description: "A Digital Edition of John Derricke's <em>Image of Irelande with a Discoverie of Woodkarne</em>"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true             # show article excerpts instead of archive list on the home page
show_frame: true                # display a grey frame on large screens
show_sidebar: false             # show a sidebar instead of the usual header
show_minimal: false             # remove all clutter

#show_frame: "/assets/images/background.svg"

# Menu                          # for available icons see https://fontawesome.com/v5/icons/

navigation:                     # accepts {file, title, url, icon, sidebaricon}
  - {file: "README.md", sidebaricon: address-card}
  - {file: "/src/content/image.xml", sidebaricon: book}

external:                       # accepts {file, title, url, icon, sidebaricon}
  - {title: Mail, icon: envelope, url: "mailto:asilva@york.cuny.edu"}
  - {title: Github, icon: github, url: "https://github.com/andiesilva/digitalderricke"}

plugins:
 - jekyll-feed
